# Generated by Django 4.2.23 on 2025-08-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='purpose',
        ),
        migrations.AddField(
            model_name='user',
            name='translation_category',
            field=models.CharField(blank=True, choices=[('zh', 'Chinese'), ('en', 'English'), ('ja', 'Japanese'), ('ja', 'Japanese'), ('mn', 'Mongolian'), ('mm', 'Myanmar'), ('ne', 'Nepali'), ('ko', 'Korean'), ('th', 'Thai'), ('uz', 'Uzbek'), ('vi', 'Vietnamese')], max_length=5, null=True, verbose_name='번역'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_language',
            field=models.CharField(choices=[('zh', 'Chinese'), ('en', 'English'), ('ja', 'Japanese'), ('ja', 'Japanese'), ('mn', 'Mongolian'), ('mm', 'Myanmar'), ('ne', 'Nepali'), ('ko', 'Korean'), ('th', 'Thai'), ('uz', 'Uzbek'), ('vi', 'Vietnamese')], default='ko', max_length=5, verbose_name='언어'),
        ),
    ]
