# Generated by Django 5.2.5 on 2025-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_district_remove_user_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, choices=[('cn', '중국'), ('vn', '베트남'), ('us', '미국'), ('jp', '일본'), ('th', '태국'), ('kr', '한국'), ('ru', '러시아'), ('tw', '대만')], max_length=50, null=True, verbose_name='국적'),
        ),
        migrations.AlterField(
            model_name='user',
            name='service_language',
            field=models.CharField(choices=[('zh', 'Chinese'), ('vi', 'Vietnamese'), ('en', 'English'), ('ja', 'Japanese'), ('th', 'Thai'), ('ko', 'Korean'), ('ru', 'Russian')], default='ko', max_length=5, verbose_name='언어'),
        ),
        migrations.AlterField(
            model_name='user',
            name='translation_category',
            field=models.CharField(blank=True, choices=[('zh', 'Chinese'), ('vi', 'Vietnamese'), ('en', 'English'), ('ja', 'Japanese'), ('th', 'Thai'), ('ko', 'Korean'), ('ru', 'Russian')], max_length=5, null=True, verbose_name='번역'),
        ),
    ]
