# Generated by Django 5.2.5 on 2025-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_mode',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
