# Generated by Django 4.2.23 on 2025-08-16 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_1', models.BooleanField(default=False, verbose_name='성격문장 1')),
                ('personality_2', models.BooleanField(default=False, verbose_name='성격문장 2')),
                ('personality_3', models.BooleanField(default=False, verbose_name='성격문장 3')),
                ('personality_4', models.BooleanField(default=False, verbose_name='성격문장 4')),
                ('personality_5', models.BooleanField(default=False, verbose_name='성격문장 5')),
                ('personality_6', models.BooleanField(default=False, verbose_name='성격문장 6')),
                ('personality_7', models.BooleanField(default=False, verbose_name='성격문장 7')),
                ('personality_8', models.BooleanField(default=False, verbose_name='성격문장 8')),
                ('personality_9', models.BooleanField(default=False, verbose_name='성격문장 9')),
                ('personality_10', models.BooleanField(default=False, verbose_name='성격문장 10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_reviewer', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reviewer', 'reviewed_user')},
            },
        ),
    ]
