# Generated by Django 4.2.23 on 2025-08-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='personality_11',
            field=models.BooleanField(default=False, verbose_name='적극적이고 활발해요'),
        ),
        migrations.AddField(
            model_name='review',
            name='personality_12',
            field=models.BooleanField(default=False, verbose_name='신뢰할 수 있어요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_1',
            field=models.BooleanField(default=False, verbose_name='이야기를 잘 들어줘요 1'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_10',
            field=models.BooleanField(default=False, verbose_name='정직하고 솔직해요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_2',
            field=models.BooleanField(default=False, verbose_name='유머 감각이 뛰어나요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_3',
            field=models.BooleanField(default=False, verbose_name='대화가 재미있어요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_4',
            field=models.BooleanField(default=False, verbose_name='긍정적인 마인드예요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_5',
            field=models.BooleanField(default=False, verbose_name='친근하고 따뜻해요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_6',
            field=models.BooleanField(default=False, verbose_name='배려심이 깊어요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_7',
            field=models.BooleanField(default=False, verbose_name='지식이 풍부해요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_8',
            field=models.BooleanField(default=False, verbose_name='호기심이 많아요'),
        ),
        migrations.AlterField(
            model_name='review',
            name='personality_9',
            field=models.BooleanField(default=False, verbose_name='이해심이 많아요'),
        ),
    ]
